/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapacidadeRouteImport } from './routes/capacidade'
import { Route as UzRouteImport } from './routes/uz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacidadeRoute = CapacidadeRouteImport.update({
  id: '/capacidade',
  path: '/capacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const UzRoute = UzRouteImport.update({
  id: '/uz',
  path: '/uz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capacidade': typeof CapacidadeRoute
  '/uz': typeof UzRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capacidade': typeof CapacidadeRoute
  '/uz': typeof UzRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capacidade': typeof CapacidadeRoute
  '/uz': typeof UzRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/capacidade' | '/uz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/capacidade' | '/uz'
  id: '__root__' | '/' | '/capacidade' | '/uz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapacidadeRoute: typeof CapacidadeRoute
  UzRoute: typeof UzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacidade': {
      id: '/capacidade'
      path: '/capacidade'
      fullPath: '/capacidade'
      preLoaderRoute: typeof CapacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uz': {
      id: '/uz'
      path: '/uz'
      fullPath: '/uz'
      preLoaderRoute: typeof UzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapacidadeRoute: CapacidadeRoute,
  UzRoute: UzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
